# Questão 1

In [22]:
import numpy as np

arr = np.arange(50)

In [23]:
arr_atualizado = arr[arr % 2]
print(arr_atualizado)

[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1]


In [24]:
arr_atualizado = arr[arr>5]
print(arr_atualizado)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
arr_atualizado = arr[arr <= 10]
print(arr_atualizado)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [26]:
arr_atualizado = arr[(arr != 1) | (arr != 3)]
print(arr_atualizado)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


# Questão 2

Enunciado

Agora, vamos explorar os arrays aleatórios e máscaras. Faça o que se pede:

a) Crie um array aleatório de 15 itens entre 0 e 100;

b) Qual o maior número do array?

c) Qual a sua posição?

d) Verifique quais números do array são maior que 10;

e) Salve em uma nova lista apenas os itens entre 10 e 30.


In [21]:
import numpy as np

arrayAleatorio = np.random.randint(0, 100, 16)

print(arrayAleatorio)

maximo = arrayAleatorio.max()
print(maximo)

print(np.where(arrayAleatorio == maximo))

maiorque10 = arrayAleatorio[arrayAleatorio > 10]
print(maiorque10)

entre10e30 = arrayAleatorio[(arrayAleatorio > 10) & (arrayAleatorio < 30)]
print(entre10e30)

[75 19 42 56 78 13 75 49 32 49  8 60 94 56 47 62]
94
(array([12]),)
[75 19 42 56 78 13 75 49 32 49 60 94 56 47 62]
[19 13]
