In [ ]:
- Lógica de Programação 
- Programação Orientada a Objeto
- Aplicação - requests, BeautifulSoup (bs4)

Bibliotecas e APIs
SciPy - Scientific Python Stack

NumPy - computação numérica
Pandas - conjuntos de dados, tabelas, planilhas etc
Matplotlib - visualização de dados (gráficos)
Seaborn - visualização de dados

scikit-learn

Turma 782
Prof. Rafael
Prof. Luis
Prof. Helder



In [1]:
import numpy as np


# numpy array
exemplo1 = np.array([1, 3, 5, 7, 9])

exemplo1

array([1, 3, 5, 7, 9])

In [2]:
# numpy array é indexado:
exemplo1[3]

7

In [3]:
# usando slices
exemplo1[1:3]

array([3, 5])

In [4]:
exemplo1[0:5:2]

array([1, 5, 9])

In [5]:
# numpy array é mutável:
exemplo1[3] = 10

exemplo1

array([ 1,  3,  5, 10,  9])

In [6]:
# cuidado com os tipos!
exemplo1[3] = 3.14

exemplo1

array([1, 3, 5, 3, 9])

In [7]:
exemplo1.dtype # mostra o tipo dos dados armazenados nesse array

dtype('int32')

In [8]:
exemplo2 = np.array([1.0, 3.0, 5.0, 7.0, 9.0])

exemplo2

array([1., 3., 5., 7., 9.])

In [9]:
exemplo2.dtype

dtype('float64')

In [10]:
exemplo2[3] = 3.14

exemplo2

array([1.  , 3.  , 5.  , 3.14, 9.  ])

In [11]:
exemplo1 * 5

array([ 5, 15, 25, 15, 45])

In [12]:
exemplo1 - 3

array([-2,  0,  2,  0,  6])

In [13]:
vezesDez = exemplo1 * 10

vezesDez

array([10, 30, 50, 30, 90])

In [14]:
operacaoVetorial = vezesDez - exemplo1

operacaoVetorial # note que precisamos sempre usar arrays de mesmo tamanho

array([ 9, 27, 45, 27, 81])

In [15]:
teste = np.array([1, 1, 1, 1, 1, 1])

operacaoVetorial - teste

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [16]:
arraydatupla = np.array((1, 2, 3))

arraydatupla

array([1, 2, 3])

In [17]:
soma12 = exemplo1 + exemplo2

soma12

array([ 2.  ,  6.  , 10.  ,  6.14, 18.  ])

In [18]:
lista = [1, 2, 3]
tupla = (4, 5, 6)

array1 = np.array(lista)
array2 = np.array(tupla)

array1 - array2

array([-3, -3, -3])

In [22]:
arrayaleatorio = np.random.randint(1, 5, 10)

arrayaleatorio

array([4, 4, 3, 4, 1, 4, 2, 3, 3, 1])

In [24]:
# soma
arrayaleatorio.sum()

29

In [25]:
arrayaleatorio.mean()

2.9

In [26]:
arrayaleatorio.max()

4

In [27]:
arrayaleatorio.min()

1

In [30]:
np.median(arrayaleatorio)

3.0

In [31]:
np.std(arrayaleatorio)

1.1357816691600546

In [32]:
exemploAleatorio = np.random.randint(1, 100, 20)

exemploAleatorio

array([32, 25, 10, 40, 54, 46, 50, 91, 36, 39, 76, 12, 51, 90, 48, 17,  9,
       43, 99, 46])

In [33]:
# máscara:
mascara = exemploAleatorio > 50

mascara

array([False, False, False, False,  True, False, False,  True, False,
       False,  True, False,  True,  True, False, False, False, False,
        True, False])

In [38]:
# aplicando a máscara diretamente no array:
maioresque50 = exemploAleatorio[mascara]

maioresque50

array([54, 91, 76, 51, 90, 99])

In [39]:
# podemos ordenar, se necessário:
maioresque50.sort()

maioresque50

array([51, 54, 76, 90, 91, 99])

In [40]:
# a etapa de criar a máscara não precisa ser explícita e pode ser usada diretamente nos colchetes:
menorque50 = exemploAleatorio[exemploAleatorio < 50]

menorque50

array([32, 25, 10, 40, 46, 36, 39, 12, 48, 17,  9, 43, 46])

In [41]:
entre30e60 = exemploAleatorio[(exemploAleatorio > 30) & (exemploAleatorio < 60)] # & = versão numpy para "and"

entre30e60

array([32, 40, 54, 46, 50, 36, 39, 51, 48, 43, 46])

In [42]:
menor30oumaior60 = exemploAleatorio[ (exemploAleatorio <= 30) | (exemploAleatorio >= 60) ] # | = versão numpy para "or"

menor30oumaior60

array([25, 10, 91, 76, 12, 90, 17,  9, 99])

In [43]:
arraySequencial1 = np.arange(10)
arraySequencial1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arraySequencial2 = np.arange(1, 10)
arraySequencial2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arraySequencial3 = np.arange(1, 10, 3)
arraySequencial3

array([1, 4, 7])

In [46]:
espacolinear = np.linspace(10, 20, 5) # valor inicial, valor final, QUANTIDADE de valores

espacolinear

array([10. , 12.5, 15. , 17.5, 20. ])

In [47]:
for elemento in espacolinear:
    print(elemento)

10.0
12.5
15.0
17.5
20.0


# Exercícios

1) Dado o array:
```python
arr = np.arange(50)
```
Selecione a alternativa INCORRETA na utilização de filtros e máscaras neste Numpy array.

- [ ] 
```python
arr_atualizado = arr[arr <= 10]
print(arr_atualizado)
```

- [ ] 
```python
arr_atualizado = arr[arr % 2]
print(arr_atualizado)
```

- [ ]
```python
arr_atualizado = arr[(arr != 1) | (arr != 3)]
print(arr_atualizado)
```

- [ ]
```python
arr_atualizado = arr[arr>5]
print(arr_atualizado)
```

