# Questão 3

Nosso próximo foco serão as matrizes. Faça o que se pede:

a) Gere uma matriz (3,2) com números linearmente espaçados entre 0 e 100 e intervalos de 20, usando o np.linspace();

b) Gere uma matriz aleatória (5,2) com números entre 0 e 100;

c) Crie um array com as dimensões apropriadas que, quando multiplicado pela matriz do item a), devolva essa mesma matriz. Use o método np.matmul().

In [21]:
import numpy as np

matrizA = np.linspace(0, 100, num = 6).reshape(3,2)
print(matrizA)

matrizB = np.random.randint(0, high = 101, size = 10).reshape(5,2)

print(matrizB)

ident2 = np.identity(2)
multMatrizes = np.matmul(matrizA, ident2)

print(multMatrizes)

[[  0.  20.]
 [ 40.  60.]
 [ 80. 100.]]
[[15 54]
 [55 41]
 [35 39]
 [94 98]
 [18 59]]
[[  0.  20.]
 [ 40.  60.]
 [ 80. 100.]]


# Exercícios extras

1) Crie dois arrays de tamanho 5 com números aleatórios entre 0 e 100.

In [24]:
array1 = np.random.randint(0, 101, 5)

print(array1)

array2 = np.random.randint(0, 101, 5)

print(array2)

[32 12 99 31 46]
[67 30 35 58 79]


2) Crie uma matriz de 2 linhas e 5 colunas a partir dos arrays do exercício anterior.

In [26]:
matrizV = np.vstack([array1, array2])

matrizV

array([[32, 12, 99, 31, 46],
       [67, 30, 35, 58, 79]])

3) Exiba na tela o maior valor de cada linha, e depois de cada coluna da matriz do exercício 2.


In [27]:
maximoLinha = matrizV.max(axis = 1)
maximoColuna = matrizV.max(axis = 0)

print(maximoLinha)
print(maximoColuna)

[99 79]
[67 30 99 58 79]


4) Crie um array de tamanho 10 também com números aleatórios entre 0 e 100.

In [30]:
array10 = np.random.randint(0, 101, 10)

print(array10)

[89 45 32 49 78 74 94 53 63 80]


5) Utilizando o reshape, crie uma matriz a partir do array anterior com as dimensões adequadas e calcule o produto matricial entre a matriz do exercício 2 e ela.

In [39]:
matriz10 = array10.reshape((int(len(array10)/matrizV.ndim)), matrizV.ndim)

print(matriz10)

[[89 45]
 [32 49]
 [78 74]
 [94 53]
 [63 80]]


In [42]:
matrizV10 = np.matmul(matrizV, matriz10)
matrizV10

array([[16766, 14677],
       [20082, 16469]])

6) Calcule o produto matricial entre o resultado do exercício 5 e a matriz identidade e exiba o resultado deste produto na tela.

In [46]:
identV10 = np.identity(matrizV10.ndim)
mult6 = np.matmul(matrizV10, identV10)

mult6

array([[16766., 14677.],
       [20082., 16469.]])

7) Calcule o produto matricial entre a matriz do exercício 5 e a sua transposta.

In [50]:
print(np.matmul(matrizV10, matrizV10.T))

[[496513085 578410325]
 [578410325 674514685]]
