In [1]:
import numpy as np

# numpy array
array1 = np.array([1, 3, 5, 7, 9])

array1

array([1, 3, 5, 7, 9])

In [2]:
maior = array1.max()

maior

9

In [3]:
array2 = np.array([0, 2, 4, 6, 8])

subtracao = array2 - array1

subtracao

array([-1, -1, -1, -1, -1])

In [4]:
array1[2]

5

In [5]:
array1[ array1 > 5 ]

array([7, 9])

In [6]:
#######
preenchidoZeros = np.zeros(5) # array preenchido com 5 números 0

preenchidoZeros

array([0., 0., 0., 0., 0.])

In [7]:
preenchidoUns = np.ones(10) # array preenchido com 10 números 1

preenchidoUns

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
seteNumerosDez = np.ones(7) * 10 # preenchendo com um valor arbitrário (10) - forma 1

seteNumerosDez

array([10., 10., 10., 10., 10., 10., 10.])

In [9]:
seisNumerosDez = np.full(6, 10)

seisNumerosDez

array([10, 10, 10, 10, 10, 10])

In [10]:
###### Matrizes
seisNumerosDez.ndim # número de dimensões de uma matriz

1

In [11]:
seisNumerosDez.shape # formato da matriz

(6,)

In [12]:
matriz1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

matriz1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
matriz1.ndim # número de dimensões

2

In [15]:
matriz1.shape # "formato" da matriz

(3, 3)

In [16]:
matriz2 = np.array([[4, 5, 6],[7, 8, 9]])

matriz2.shape

(2, 3)

In [17]:
matrizUns = np.ones((3, 3))

matrizUns

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
soma = matriz1 + matrizUns

soma

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [19]:
# acessando elementos individuais:
soma[1][2]

7.0

In [20]:
# forma mais COMUM de acessar os elementos individuais:
soma[1, 2]

7.0

In [21]:
# pegando uma linha inteira:

# 1o jeito:
soma[1]

array([5., 6., 7.])

In [22]:
# 2o jeito:
soma[2, :]

array([ 8.,  9., 10.])

In [23]:
# pegando uma COLUNA inteira:
soma[:, 0]

array([2., 5., 8.])

In [25]:
linha1 = np.array([1, 5, 9])
linha2 = np.array([8, 3, 6])

matrizV = np.vstack([linha1, linha2])

matrizV

array([[1, 5, 9],
       [8, 3, 6]])

In [41]:
linha1s = linha1.reshape(3, 1)


array([[1],
       [5],
       [9]])

In [43]:
linha2s = linha2.reshape(3,1)

matrizV2 = np.hstack([linha1s, linha2s])

matrizV2

array([[1, 8],
       [5, 3],
       [9, 6]])

In [26]:
# e se fossem colunas?
matrizH = np.hstack([linha1, linha2])

matrizH

array([1, 5, 9, 8, 3, 6])

In [27]:
# matriz transposta:
transposta = matrizV.T

transposta

array([[1, 8],
       [5, 3],
       [9, 6]])

In [28]:
# mudando o formato de uma matriz:
matrizNova = matrizH.reshape(3, 2)

matrizNova

array([[1, 5],
       [9, 8],
       [3, 6]])

In [29]:
matrizNova.reshape(2, 3) # você precisa ter o número certo de elementos!

array([[1, 5, 9],
       [8, 3, 6]])

In [30]:
matrizNova.reshape(5, 2)

ValueError: cannot reshape array of size 6 into shape (5,2)

In [34]:
matrizNova.max()

9

In [35]:
matrizNova.max(axis=0) # maior de cada coluna, axis = 0

array([9, 8])

In [36]:
matrizNova.max(axis=1) # maior de cada linha, axis = 1

array([5, 9, 6])

In [44]:
mA = np.array([[1, 2],[3, 4]])
mB = np.array([[5, 6], [7, 8]])
               
mA * mB # multiplicação elemento-a-elemento

array([[ 5, 12],
       [21, 32]])

In [45]:
np.matmul(mA, mB) # multiplicação de matrizes (álgebra linear)

array([[19, 22],
       [43, 50]])

In [46]:
identidade = np.identity(5)

identidade

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.linalg.det(mA)

-2.0000000000000004

In [48]:
mA @ mB # np.matmul(mA, mB)

array([[19, 22],
       [43, 50]])

In [56]:
vet1 = np.array([1, 2, 3])
vet2 = np.array([4, 5, 6])

np.dot(vet1, vet2)


32

# Exercícios extras

1) Crie dois arrays de tamanho 5 com números aleatórios entre 0 e 100.

2) Crie uma matriz de 2 linhas e 5 colunas a partir dos arrays do exercício anterior.

3) Exiba na tela o maior valor de cada linha, e depois de cada coluna da matriz do exercício 2.

4) Crie um array de tamanho 10 também com números aleatórios entre 0 e 100.

5) Utilizando o reshape, crie uma matriz a partir do array anterior com as dimensões adequadas e calcule o produto matricial entre a matriz do exercício 2 e ela.

6) Calcule o produto matricial entre o resultado do exercício 5 e a matriz identidade e exiba o resultado deste produto na tela.

7) Calcule o produto matricial entre a matriz do exercício 5 e a sua transposta.